  
version: '3'

services:
  fastapi:
    build: ./app
    # image: tiangolo/uvicorn-gunicorn-fastapi:python3.6
    container_name: fastapi
    command: /start-reload.sh
    ports:
      - 80:80
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db