version: "3"
services:
  frontend:
    build: ./frontend
    command: yarn dev
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0

  fastapi:
    build: ./backend
    container_name: fastapi
    # command: /start-reload.sh
    # command: bash
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app
    environment:
      # - DATABASE_URL=sqlite:////app/app/test.db
    tty: true
